jobs:

- name: deployLoanK
  job:
    deploy:
      contract: loan.sol      
      wait: true

- name: initialise
  job:
    call:
      destination: $deployLoanK
      data: initialise d5d549e5431325b347d7c371b28ef9358d2436d4f5e6732485b2820ef0ed8e81 C8561C44A527AFF4DB24AC7F977D1A590E7951A3 6EAD9DA629368A1847C40F451E8B5C1D31E0E569
      wait: true

- name: addBorrowerA
  job:
    call:
      destination: $deployLoanK
      data: addBorrower 7959542D88FA0FE95A62B6701E0F276DC137D990
      wait: true

- name: addBorrowerB
  job:
    call:
      destination: $deployLoanK
      data: addBorrower 478D68A4159C76AECBC38B0D901C014FDB12B676
      wait: true

- name: queryStatus_1
  job:
    query-contract:
      destination: $deployLoanK
      data: getStatus

- name: queryExecutor
  job:
    query-contract:
      destination: $deployLoanK
      data: getExecutor

- name: queryHashOfContract
  job:
    query-contract:
      destination: $deployLoanK
      data: getHashOfContract

- name: queryLender
  job:
    query-contract:
      destination: $deployLoanK
      data: getLender

- name: queryCounterFraud
  job:
    query-contract:
      destination: $deployLoanK
      data: getCounterFraud

- name: queryBorrowerCount
  job:
    query-contract:
      destination: $deployLoanK
      data: getBorrowerCount

- name: queryBorrowerA
  job:
    query-contract:
      destination: $deployLoanK
      data: getBorrower 0
    
- name: queryBorrowerB
  job:
    query-contract:
      destination: $deployLoanK
      data: getBorrower 1
      
- name: querySignatureCount
  job:
    query-contract:
      destination: $deployLoanK
      data: getSignatureCount

- name: signBorrowerA
  job:
    call:
      source: 7959542D88FA0FE95A62B6701E0F276DC137D990
      destination: $deployLoanK
      data: sign d5d549e5431325b347d7c371b28ef9358d2436d4f5e6732485b2820ef0ed8e81
      wait: true

- name: signBorrowerB
  job:
    call:
      source: 478D68A4159C76AECBC38B0D901C014FDB12B676
      destination: $deployLoanK
      data: sign d5d549e5431325b347d7c371b28ef9358d2436d4f5e6732485b2820ef0ed8e81
      wait: true

- name: querySignatureCount
  job:
    query-contract:
      destination: $deployLoanK
      data: getSignatureCount

- name: queryStatus_2
  job:
    query-contract:
      destination: $deployLoanK
      data: getStatus


- name: approve
  job:
    call:
      source: 6EAD9DA629368A1847C40F451E8B5C1D31E0E569
      destination: $deployLoanK
      data: approved d5d549e5431325b347d7c371b28ef9358d2436d4f5e6732485b2820ef0ed8e81
      wait: true
      
- name: queryStatus_3
  job:
    query-contract:
      destination: $deployLoanK
      data: getStatus

- name: pay
  job:
    call:
      source: C8561C44A527AFF4DB24AC7F977D1A590E7951A3
      destination: $deployLoanK
      data: paid d5d549e5431325b347d7c371b28ef9358d2436d4f5e6732485b2820ef0ed8e81
      wait: true

- name: queryStatus_4
  job:
    query-contract:
      destination: $deployLoanK
      data: getStatus

      
- name: assertStatus
  job:
    assert:
      key: $queryStatus_4
      relation: eq
      val: 3
