jobs:

- name: deployLoanK
  job:
    deploy:
      contract: loan.sol      
      wait: true

- name: queryStatus
  job:
    query-contract:
      destination: $deployLoanK
      data: getStatus

- name: queryExecutor
  job:
    query-contract:
      destination: $deployLoanK
      data: getExecutor

- name: queryHashOfContract
  job:
    query-contract:
      destination: $deployLoanK
      data: getHashOfContract

- name: assertStatus
  job:
    assert:
      key: $queryStatus
      relation: eq
      val: 0
