jobs:

- name: deployBasicK
  job:
    deploy:
      contract: basic.sol
      wait: true

- name: initialise
  job:
    call:
      destination: $deployBasicK
      data: initialise 42 3 foo
      wait: true
      
- name: queryStateIntA_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getStateIntA

- name: queryStateIntB_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getStateIntB

      
- name: queryStateString_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getStateString
      
- name: setStateIntA
  job:
    call:
      destination: $deployBasicK
      data: setStateIntA 666
      wait: true

- name: setStateIntB
  job:
    call:
      destination: $deployBasicK
      data: setStateIntB 999
      wait: true

- name: setStateString
  job:
    call:
      destination: $deployBasicK
      data: setStateString bar
      wait: true

- name: queryStateIntA_Set
  job:
    query-contract:
      destination: $deployBasicK
      data: getStateIntA

- name: queryStateIntB_Set
  job:
    query-contract:
      destination: $deployBasicK
      data: getStateIntB

- name: queryStateString_Set
  job:
    query-contract:
      destination: $deployBasicK
      data: getStateString

      
- name: assertStateIntA_Construction
  job:
    assert:
      key: $queryStateIntA_Construction
      relation: eq
      val: 42

- name: assertStateIntB_Construction
  job:
    assert:
      key: $queryStateIntB_Construction
      relation: eq
      val: 3

- name: assertStateString_Construction
  job:
    assert:
      key: $queryStateString_Construction
      relation: eq
      val: foo
      
- name: assertStateIntA_Set
  job:
    assert:
      key: $queryStateIntA_Set
      relation: eq
      val: 666

- name: assertStateIntB_Set
  job:
    assert:
      key: $queryStateIntB_Set
      relation: eq
      val: 999

- name: assertStateStringAfter
  job:
    assert:
      key: $queryStateString_Set
      relation: eq
      val: bar
