jobs:

- name: deployBasicK
  job:
    deploy:
      contract: basic.sol
#      data: 42 3 foo
      wait: true

- name: initialise
  job:
    call:
      destination: $deployBasicK
      data: initialise 42 3 foo 
      wait: true
      
- name: queryA_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getA

- name: queryB_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getB

      
- name: queryC_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getC

- name: queryCreator_Construction
  job:
    query-contract:
      destination: $deployBasicK
      data: getCreator

- name: addUserA
  job:
    call:
      destination: $deployBasicK
      data: addUser C8561C44A527AFF4DB24AC7F977D1A590E7951A3
      wait: true

- name: addUserB
  job:
    call:
      destination: $deployBasicK
      data: addUser 7959542D88FA0FE95A62B6701E0F276DC137D990
      wait: true

      
- name: queryUserCount
  job:
    query-contract:
      destination: $deployBasicK
      data: getUserCount

- name: queryFirstUser
  job:
    query-contract:
      destination: $deployBasicK
      data: getUser 0

- name: querySecondUser
  job:
    query-contract:
      destination: $deployBasicK
      data: getUser 1

      
- name: setA
  job:
    call:
      destination: $deployBasicK
      data: setA 666
      wait: true

- name: setB
  job:
    call:
      destination: $deployBasicK
      data: setB 999
      wait: true

- name: setC
  job:
    call:
      destination: $deployBasicK
      data: setC bar
      wait: true

- name: queryA_Set
  job:
    query-contract:
      destination: $deployBasicK
      data: getA

- name: queryB_Set
  job:
    query-contract:
      destination: $deployBasicK
      data: getB

- name: queryC_Set
  job:
    query-contract:
      destination: $deployBasicK
      data: getC

      
- name: assertA_Construction
  job:
    assert:
      key: $queryA_Construction
      relation: eq
      val: 42

- name: assertB_Construction
  job:
    assert:
      key: $queryB_Construction
      relation: eq
      val: 3

- name: assertC_Construction
  job:
    assert:
      key: $queryC_Construction
      relation: eq
      val: foo
      
- name: assertA_Set
  job:
    assert:
      key: $queryA_Set
      relation: eq
      val: 666

- name: assertB_Set
  job:
    assert:
      key: $queryB_Set
      relation: eq
      val: 999

- name: assertC_Set
  job:
    assert:
      key: $queryC_Set
      relation: eq
      val: bar
